wip
Signed-off-by: Tamal Saha <tamal@appscode.com>

diff --git a/chart/ace-mp/templates/tests/test-connection.yaml b/chart/ace-mp/templates/tests/test-connection.yaml
--- a/chart/ace-mp/templates/tests/test-connection.yaml
+++ b/chart/ace-mp/templates/tests/test-connection.yaml
@@ -1,7 +1,7 @@
 apiVersion: v1
 kind: Pod
 metadata:
-  name: "{{ include "ace-mp.fullname" . }}-test-connection"
+  name: {{ include "ace-mp.fullname" . }}-tester
   namespace: {{ .Release.Namespace }}
   labels:
     {{- include "ace-mp.labels" . | nindent 4 }}
@@ -15,8 +15,9 @@ spec:
     command:
     - /bin/sh
     - -c
-    - sleep 500 &&
-      kubectl wait --for=create -n {{ .Release.Namespace }} service/ace-ingress-x-ace-x-{{ .Release.Name }} --timeout=5m &&
-      sleep 30 &&
-      curl -k "https://ace-ingress-x-ace-x-{{ .Release.Name }}
+    - |-
+      while ! curl -k -s "https://ace-ingress-x-ace-x-{{ .Release.Name }}" > /dev/null; do
+        echo "Request failed, retrying in 5 seconds..."
+        sleep 5
+      done
   restartPolicy: Never
diff --git a/tester.yaml b/tester.yaml
--- a/tester.yaml
+++ b/tester.yaml
@@ -10,8 +10,9 @@ spec:
     command:
     - /bin/sh
     - -c
-    - sleep 500 &&
-      kubectl wait --for=create -n ace service/ace-ingress-x-ace-x-ace-mp --timeout=5m &&
-      sleep 30 &&
-      curl -k "https://ace-ingress-x-ace-x-ace-mp"
+    - |-
+      while ! curl -k -s "https://ace-ingress-x-ace-x-ace-mp" > /dev/null; do
+        echo "Request failed, retrying in 5 seconds..."
+        sleep 5
+      done
   restartPolicy: Never
